import "./auth/auth.test.js";
import "./auth/authorization.test.js";
import "./course-modules/course-modules.test.js";
import "./courses/courses.test.js";
import "./invitations/invitations.test.js";
import "./lessons/lessons.test.js";
import "./media/media.test.js";
import "./organizations/organizations.test.js";
import "./storage/storage.test.js";
